services:
  - type: web
    name: your-backend-service
    runtime: python
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: GOOGLE_API_KEY
        value: your_api_key_here
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
